sudo: required

services:
  - docker
  
before_install:
  - docker build -t masahide/tox .
  
script:
  - docker run --rm masahide/tox python2.7 --version
  - docker run --rm masahide/tox python3.6 --version
  - docker run --rm masahide/tox python3.7 --version
  - docker run --rm masahide/tox pypy --version
  - docker run --rm masahide/tox pip --version
  - docker run --rm masahide/tox tox --version
  - docker run --rm masahide/tox pipenv --version
  - docker run --rm masahide/tox make --version
  - docker run --rm masahide/tox gcc --version

notifications:
    email: false
